const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const data = fs.mkdtempSync(path.join(os.tmpdir(), 'dosenote-ui-'));
const screenshotDir = path.join(root, 'docs/screenshots');
let app;
let page;
const errors = [];
async function launch() {
  const args = [root, ...(process.env.CI && process.platform === 'linux' ? ['--no-sandbox'] : [])];
  app = await electron.launch({ args, env: { ...process.env, DOSENOTE_TEST_DATA: data } });
  page = await app.firstWindow();
  page.on('pageerror', error => errors.push(error.message));
  await page.locator('#today-title').waitFor();
}
async function add(name, amount, doses = '1', frequency = 'daily') {
  await page.locator('#settings-tab').click();
  await page.locator('#name').fill(name);
  await page.locator('#amount').fill(amount);
  await page.locator('#frequency').selectOption(frequency);
  if (frequency !== 'as-needed') await page.locator('#doses').selectOption(doses);
  await page.locator('#save-medication').click();
  await page.getByRole('heading', { name, exact: true }).waitFor();
}
(async () => {
  try {
    await launch();
    assert.equal(await page.locator('#empty-state').isVisible(), true);
    await add('Vitamin D', '1 tablet · 1,000 IU');
    await add('Example medication', '1 tablet · 10 mg', '2');
    await add('As-needed example', 'As prescribed', '1', 'as-needed');
    await page.locator('#today-tab').click();
    assert.equal(await page.locator('.dose-button').count(), 4);
    await page.getByRole('button', { name: 'Vitamin D, dose 1: mark as taken', exact: true }).click();
    await page.getByRole('button', { name: 'Example medication, dose 1: mark as taken', exact: true }).click();
    assert.equal(await page.locator('#progress-text').textContent(), '2 of 3 doses taken');
    await page.getByRole('button', { name: 'As-needed example, dose 1: mark as taken', exact: true }).click();
    assert.equal(await page.locator('#progress-text').textContent(), '2 of 3 doses taken');
    await page.getByRole('button', { name: 'Vitamin D, dose 1: taken; click to undo', exact: true }).click();
    assert.equal(await page.locator('#progress-text').textContent(), '1 of 3 doses taken');
    await page.getByRole('button', { name: 'Vitamin D, dose 1: mark as taken', exact: true }).click();
    await app.close();
    await launch();
    assert.equal(await page.locator('#progress-text').textContent(), '2 of 3 doses taken');
    await page.locator('#settings-tab').click();
    await page.getByRole('button', { name: 'Edit Vitamin D', exact: true }).click();
    await page.locator('#amount').fill('2 tablets · 1,000 IU each');
    await page.locator('#save-medication').click();
    await page.locator('#today-tab').click();
    await page.locator('#history summary').click();
    assert.match(await page.locator('#history-list').textContent(), /1 tablet · 1,000 IU/);
    await page.locator('#settings-tab').click();
    await page.getByRole('button', { name: 'Remove Vitamin D', exact: true }).click();
    await page.locator('#confirm-cancel').click();
    assert.equal(await page.locator('.saved-med').count(), 3);
    await page.getByRole('button', { name: 'Remove Vitamin D', exact: true }).click();
    await page.locator('#confirm-remove').click();
    await page.waitForFunction(() => document.querySelectorAll('.saved-med').length === 2);
    await add('<img src=x onerror=alert(1)>', '1 tablet');
    assert.equal(await page.locator('.saved-med img').count(), 0);
    await page.getByRole('button', { name: 'Remove <img src=x onerror=alert(1)>', exact: true }).click();
    await page.locator('#confirm-remove').click();
    await page.waitForFunction(() => document.querySelectorAll('.saved-med').length === 2);
    await add('Vitamin D', '1 tablet · 1,000 IU');
    await page.locator('#frequency').selectOption('weekly');
    await page.locator('#name').fill('Weekly example');
    await page.locator('#amount').fill('1 tablet');
    await page.locator('#save-medication').click();
    assert.equal(await page.locator('#form-error').textContent(), 'Choose at least one day of the week.');
    await page.locator('#weekdays-field input[value="1"]').check();
    await page.locator('#save-medication').click();
    await page.getByRole('heading', { name: 'Weekly example', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Remove Weekly example', exact: true }).click();
    await page.locator('#confirm-remove').click();
    await page.waitForFunction(() => document.querySelectorAll('.saved-med').length === 3);
    const backupFile = path.join(data, 'backup.json');
    await app.evaluate(({ dialog }, file) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: file }); }, backupFile);
    await page.locator('#export-backup').click();
    await page.waitForFunction(() => document.getElementById('toast').textContent === 'Backup saved.');
    assert.equal(JSON.parse(fs.readFileSync(backupFile, 'utf8')).medications.length, 3);
    await add('Temporary medication', '1 tablet');
    await app.evaluate(({ dialog }, file) => {
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] });
      dialog.showMessageBox = async () => ({ response: 0 });
    }, backupFile);
    await page.locator('#import-backup').click();
    await page.waitForFunction(() => !document.getElementById('import-backup').disabled);
    assert.equal(await page.locator('.saved-med').count(), 4);
    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1 }); });
    await page.locator('#import-backup').click();
    await page.waitForFunction(() => document.querySelectorAll('.saved-med').length === 3);
    assert.equal(await page.getByRole('heading', { name: 'Temporary medication', exact: true }).count(), 0);
    await page.locator('#today-tab').click();
    await page.getByRole('button', { name: 'Vitamin D, dose 1: mark as taken', exact: true }).click();
    await page.locator('#history summary').click();
    await page.locator('#toast').evaluate(node => { node.hidden = true; });
    await page.waitForFunction(() => !document.querySelector('button:disabled'));
    await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement.blur(); });
    await page.waitForTimeout(200);
    await page.screenshot({ path: path.join(screenshotDir, 'today.png'), fullPage: true, scale: 'css', animations: 'disabled' });
    await page.locator('#settings-tab').click();
    await page.locator('#name').fill('Your medication name');
    await page.locator('#amount').fill('Your prescribed amount');
    await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement.blur(); });
    await page.waitForTimeout(200);
    await page.screenshot({ path: path.join(screenshotDir, 'settings.png'), fullPage: true, scale: 'css', animations: 'disabled' });
    assert.deepEqual(errors, []);
    console.log('PASS: desktop UI, doses, undo, restart persistence, edit history, removal confirmation, text safety, weekly validation, backup export and confirmed restore; screenshots saved.');
  } finally {
    if (app) await app.close();
    fs.rmSync(data, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
